(()=>{'use strict';
const $=id=>document.getElementById(id), money=n=>'$'+Math.max(0,Math.round(n)).toLocaleString();
const players=['Tammy','Aron'];
const wheelValues=[5000,10000,15000,20000,25000,30000,35000,40000,45000,50000,60000,70000,75000,80000,90000,100000];
const trivia=[
['Science',[['What planet is known as the Red Planet?',['Venus','Mars','Jupiter','Mercury'],1],['What gas do plants absorb?',['Oxygen','Nitrogen','Carbon dioxide','Helium'],2],['How many bones are in an adult human body?',['106','206','306','406'],1]]],
['History',[['Who was the first U.S. president?',['Lincoln','Washington','Adams','Jefferson'],1],['The pyramids of Giza are in which country?',['Mexico','Egypt','Peru','India'],1],['Which ship sank in 1912?',['Mayflower','Titanic','Bismarck','Victory'],1]]],
['Geography',[['What is the largest ocean?',['Atlantic','Indian','Pacific','Arctic'],2],['What is the capital of Colorado?',['Aspen','Denver','Boulder','Pueblo'],1],['Which continent is Brazil in?',['Europe','Africa','South America','Asia'],2]]],
['Movies',[['Who lives in a pineapple under the sea?',['Shrek','SpongeBob','Nemo','Simba'],1],['What color is the Grinch?',['Blue','Red','Green','Purple'],2],['In Frozen, who is the snowman?',['Olaf','Sven','Kristoff','Hans'],0]]],
['General',[['How many sides does a hexagon have?',['5','6','7','8'],1],['What is 12 × 12?',['124','132','144','154'],2],['Which animal is the largest?',['Elephant','Blue whale','Giraffe','Hippo'],1]]]
];
const state={started:false,turn:0,target:1000000,scores:{Tammy:0,Aron:0},pending:false,pendingMode:null,winner:null,history:[],undo:null,uses:{},limit:3,wheelUsed:{Tammy:false,Aron:false},bankruptcies:{Tammy:0,Aron:0},rescueSpin:false,angle:0,spinning:false,bj:{deck:[],bet:0,chips:[],player:[],dealer:[],active:false},box:null,secret:null,triviaUsed:new Set()};
function current(){return players[state.turn]}
function other(p=current()){return p==='Tammy'?'Aron':'Tammy'}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function log(msg){state.history.unshift(msg);state.history=state.history.slice(0,60)}
function initUses(){for(const p of players)state.uses[p]={blackjack:0,box:0,trivia:0,secret:0}}
function useMode(mode){if(!state.started||state.winner)return false;if(state.pending){toast('Complete the current turn first.');return false}if(state.uses[current()][mode]>=state.limit){toast(`${current()} has used this game ${state.limit} times.`);return false}state.undo=JSON.parse(JSON.stringify({scores:state.scores,uses:state.uses,turn:state.turn,bankruptcies:state.bankruptcies,wheelUsed:state.wheelUsed}));state.uses[current()][mode]++;state.pendingMode=mode;return true}
function snapshot(){state.undo=JSON.parse(JSON.stringify({scores:state.scores,uses:state.uses,turn:state.turn,bankruptcies:state.bankruptcies,wheelUsed:state.wheelUsed}))}
function setPending(result,info='Press Complete Turn.'){state.pending=true;$('result').textContent=result;$('info').textContent=info;update()}
function startGame(){state.started=true;state.turn=0;state.target=Math.max(100000,+$('goal').value||1000000);state.limit=Math.max(1,+$('modeLimit').value||3);state.scores={Tammy:0,Aron:0};state.pending=false;state.pendingMode=null;state.winner=null;state.history=[];state.wheelUsed={Tammy:false,Aron:false};state.bankruptcies={Tammy:0,Aron:0};state.rescueSpin=false;state.triviaUsed=new Set();initUses();resetBJ();resetBox();resetSecret();$('setup').classList.add('hidden');log('Game Night started. Tammy goes first.');$('result').textContent='Tammy chooses the first game.';$('info').textContent='Each player gets one normal wheel spin for the entire game.';update();drawWheel()}
function completeTurn(){if(!state.started)return toast('Start the game first.');if(!state.pending)return toast('Finish a game first.');if(state.winner)return;state.pending=false;state.pendingMode=null;state.turn=1-state.turn;state.rescueSpin=false;$('result').textContent=`${current()}'s turn.`;$('info').textContent='Choose a game.';update()}
function skipTurn(){if(!state.started||state.winner)return;if(state.pending)return toast('Complete the active game first.');state.turn=1-state.turn;log(`Turn skipped. ${current()} is up.`);update()}
function undo(){if(!state.undo||state.pendingMode==='wheel')return toast('Nothing available to undo.');Object.assign(state,state.undo);state.undo=null;state.pending=false;state.pendingMode=null;update();toast('Last result undone.')}
function finish(winner,reason='reached the goal'){state.winner=winner;state.pending=false;$('winnerTitle').textContent=`${winner} wins!`;$('winnerText').textContent=`${winner} ${reason}. Final score: ${money(state.scores[winner])}.`;$('winner').classList.remove('hidden');log(`${winner} wins the game.`);update()}
function handleBankruptcy(player,before,after){if(before<=0||after>0||state.winner)return;state.bankruptcies[player]++;if(state.bankruptcies[player]>=2){finish(other(player),`wins because ${player} went bankrupt a second time`);return}state.turn=players.indexOf(player);state.rescueSpin=true;state.pending=false;state.pendingMode=null;$('result').textContent=`${player} is bankrupt for the first time.`;$('info').textContent=`${player} gets one rescue wheel spin now.`;openPane('wheel');log(`${player} reached $0 and received a rescue spin.`);update()}
function changeMoney(player,delta,reason){const before=state.scores[player];state.scores[player]=Math.max(0,before+delta);log(`${player} ${delta>=0?'won':'lost'} ${money(Math.abs(delta))} — ${reason}.`);if(state.scores[player]>=state.target){finish(player);return}handleBankruptcy(player,before,state.scores[player])}
function update(){const p=current();$('turn').textContent=state.started?(state.rescueSpin?`${p}: RESCUE WHEEL SPIN`:`${p}'s turn`):'Start the game';$('targetMoney').textContent=money(state.target);for(const name of players){$(name.toLowerCase()+'Score').textContent=money(state.scores[name]);$(name.toLowerCase()+'Bar').style.width=Math.min(100,state.scores[name]/state.target*100)+'%';$(name.toLowerCase()+'Bankruptcy').textContent=state.bankruptcies[name]?'Rescue used — next bankruptcy loses':'Rescue wheel available'}$('completeBtn').disabled=!state.pending||!!state.winner;$('skipBtn').disabled=!state.started||state.pending||!!state.winner;$('undoBtn').disabled=!state.undo||state.pendingMode==='wheel';$('spinBtn').disabled=!state.started||state.pending||state.spinning||(!state.rescueSpin&&state.wheelUsed[p]);$('spinBtn').textContent=state.rescueSpin?'USE RESCUE SPIN':state.wheelUsed[p]?'WHEEL SPIN USED':'SPIN ONCE';$('history').innerHTML=state.history.map(x=>`<div>${x}</div>`).join('');$('uses').innerHTML=players.map(n=>`<div class="use"><b>${n}</b><br>Blackjack ${state.uses[n]?.blackjack||0}/${state.limit}<br>Shut Box ${state.uses[n]?.box||0}/${state.limit}<br>Trivia ${state.uses[n]?.trivia||0}/${state.limit}<br>Secret ${state.uses[n]?.secret||0}/${state.limit}<br>Wheel ${state.wheelUsed[n]?'used':'available'}</div>`).join('');renderSecret();renderBJ()}
function openPane(id){document.querySelectorAll('.pane').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.pane===id));if(id==='wheel')requestAnimationFrame(drawWheel)}
function drawWheel(){const c=$('wheelCanvas'),ctx=c.getContext('2d'),d=Math.min(900,Math.max(500,c.clientWidth*2||700));if(c.width!==d){c.width=c.height=d}const r=d/2,seg=Math.PI*2/wheelValues.length;ctx.clearRect(0,0,d,d);ctx.save();ctx.translate(r,r);ctx.rotate(state.angle);wheelValues.forEach((v,i)=>{ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r-12,i*seg,(i+1)*seg);ctx.closePath();ctx.fillStyle=['#ef476f','#118ab2','#06d6a0','#8338ec','#ff9f1c','#3a86ff'][i%6];ctx.fill();ctx.strokeStyle='#fff7';ctx.lineWidth=3;ctx.stroke();ctx.save();ctx.rotate((i+.5)*seg);ctx.translate(r*.62,0);ctx.rotate(Math.PI/2);ctx.fillStyle='#fff';ctx.font=`900 ${Math.max(19,d*.032)}px -apple-system`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.shadowColor='#000';ctx.shadowBlur=5;ctx.fillText('$'+v/1000+'K',0,0);ctx.restore()});ctx.beginPath();ctx.arc(0,0,r*.16,0,Math.PI*2);ctx.fillStyle='#ffd166';ctx.fill();ctx.strokeStyle='#6a3c07';ctx.lineWidth=8;ctx.stroke();ctx.restore()}
function spinWheel(){if(state.spinning||state.pending||!state.started)return;const p=current();if(!state.rescueSpin&&state.wheelUsed[p])return toast(`${p} already used the one normal wheel spin.`);snapshot();if(!state.rescueSpin)state.wheelUsed[p]=true;state.pendingMode='wheel';state.spinning=true;update();const start=state.angle,extra=(5+Math.random()*4)*Math.PI*2,begin=performance.now(),dur=3200;function frame(now){const t=Math.min(1,(now-begin)/dur),ease=1-Math.pow(1-t,4);state.angle=start+extra*ease;drawWheel();if(t<1)requestAnimationFrame(frame);else{state.spinning=false;const seg=Math.PI*2/wheelValues.length;let pointer=((Math.PI*1.5-state.angle)%(Math.PI*2)+Math.PI*2)%(Math.PI*2);const index=Math.floor(pointer/seg)%wheelValues.length,value=wheelValues[index];changeMoney(p,value,state.rescueSpin?'bankruptcy rescue wheel':'prize wheel');state.rescueSpin=false;setPending(`${p} won ${money(value)} on the wheel.`)}}requestAnimationFrame(frame)}
function makeDeck(){const suits=['♠','♥','♦','♣'],ranks=['A','2','3','4','5','6','7','8','9','10','J','Q','K'],d=[];for(const s of suits)for(const r of ranks)d.push({s,r});for(let i=d.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[d[i],d[j]]=[d[j],d[i]]}return d}
function resetBJ(){state.bj={deck:makeDeck(),bet:0,chips:[],player:[],dealer:[],active:false};if($('bjStatus'))$('bjStatus').textContent='Choose chips, then press Deal.'}
function cardValue(hand){let total=0,aces=0;for(const c of hand){if(c.r==='A'){aces++;total+=11}else total+=['J','Q','K'].includes(c.r)?10:+c.r}while(total>21&&aces--){total-=10}return total}
function cardHTML(c,hidden=false){if(hidden)return '<div class="playing-card back"></div>';const red=c.s==='♥'||c.s==='♦';return `<div class="playing-card ${red?'red':''}"><span>${c.r}${c.s}</span><span class="card-center">${c.s}</span><span style="text-align:right">${c.r}${c.s}</span></div>`}
function renderBJ(hideDealer=false){if(!$('bjBet'))return;const b=state.bj;$('bjBet').textContent=money(b.bet);$('shoeCount').textContent=`${b.deck.length} cards remaining`;$('playerCards').innerHTML=b.player.map(c=>cardHTML(c)).join('');$('dealerCards').innerHTML=b.dealer.map((c,i)=>cardHTML(c,hideDealer&&i===1)).join('');$('playerTotal').textContent=cardValue(b.player);$('dealerTotal').textContent=hideDealer&&b.dealer.length?'?':cardValue(b.dealer);$('bjPlayer').textContent=current();$('dealBtn').disabled=!state.started||state.pending||b.active||b.bet<5000;$('hitBtn').disabled=!b.active;$('standBtn').disabled=!b.active;$('chipRack').querySelectorAll('button').forEach(x=>x.disabled=b.active||state.pending);$('betStack').innerHTML=b.chips.length?b.chips.map(v=>`<span class="stack-chip" title="${money(v)}"></span>`).join(''):'<span class="empty-bet">Tap chips to build a bet</span>'}
function addChip(v){if(state.bj.active||state.pending)return;const max=Math.max(100000,state.scores[current()]);if(state.bj.bet+v>max)return toast('That bet is above the allowed bankroll or starter limit.');state.bj.bet+=v;state.bj.chips.push(v);renderBJ()}
function undoChip(){const v=state.bj.chips.pop();if(v)state.bj.bet-=v;renderBJ()}
function clearBet(){state.bj.bet=0;state.bj.chips=[];renderBJ()}
function drawCard(){if(state.bj.deck.length<10)state.bj.deck=makeDeck();return state.bj.deck.pop()}
function dealBJ(){if(!useMode('blackjack'))return;const b=state.bj;b.player=[drawCard(),drawCard()];b.dealer=[drawCard(),drawCard()];b.active=true;state.pending=true;$('bjStatus').textContent=`${current()} bet ${money(b.bet)}. Hit or stand.`;renderBJ(true);const pv=cardValue(b.player),dv=cardValue(b.dealer);if(pv===21||dv===21)setTimeout(()=>settleBJ(),500);update()}
function hitBJ(){if(!state.bj.active)return;state.bj.player.push(drawCard());renderBJ(true);if(cardValue(state.bj.player)>=21)settleBJ()}
function standBJ(){if(!state.bj.active)return;while(cardValue(state.bj.dealer)<17)state.bj.dealer.push(drawCard());settleBJ()}
function settleBJ(){const b=state.bj;if(!b.active)return;b.active=false;const p=cardValue(b.player),d=cardValue(b.dealer),name=current();let delta=0,msg='Push.';if(p>21){delta=-b.bet;msg='Player busts.'}else if(d>21||p>d){delta=(p===21&&b.player.length===2)?Math.floor(b.bet*1.5):b.bet;msg=p===21&&b.player.length===2?'Blackjack!':'Player wins.'}else if(d>p){delta=-b.bet;msg='Dealer wins.'}changeMoney(name,delta,'Blackjack');$('bjStatus').textContent=`${msg} ${delta>=0?'+':''}${money(Math.abs(delta))}.`;setPending(`${name}: ${msg} ${delta>=0?'won':'lost'} ${money(Math.abs(delta))}.`);b.bet=0;b.chips=[];renderBJ(false)}
function resetBox(){state.box={active:false,playerIndex:0,open:[1,2,3,4,5,6,7,8,9],selected:[],roll:null,scores:{}};renderTiles();if($('die1')){$('die1').textContent='⚀';$('die2').textContent='⚀'}}
function renderTiles(){if(!$('tiles'))return;$('tiles').innerHTML=[1,2,3,4,5,6,7,8,9].map(n=>`<button class="tile ${state.box&&!state.box.open.includes(n)?'closed':''} ${state.box?.selected.includes(n)?'selected':''}" data-n="${n}">${n}</button>`).join('')}
function rollDice(){if(!state.box.active){if(!useMode('box'))return;state.box={active:true,playerIndex:0,open:[1,2,3,4,5,6,7,8,9],selected:[],roll:null,scores:{}};state.pending=true}if(state.box.roll!==null)return toast('Close pegs or end the run first.');const a=1+Math.floor(Math.random()*6),b=1+Math.floor(Math.random()*6);state.box.roll=a+b;$('die1').textContent=a;$('die2').textContent=b;$('boxStatus').textContent=`${players[state.box.playerIndex]} rolled ${a}+${b}=${a+b}. Select wooden pegs totaling ${a+b}.`;renderTiles();update()}
function toggleTile(n){const b=state.box;if(!b.active||b.roll===null||!b.open.includes(n))return;const i=b.selected.indexOf(n);if(i>=0)b.selected.splice(i,1);else b.selected.push(n);renderTiles()}
function closeTiles(){const b=state.box;if(!b.active||b.roll===null)return;const sum=b.selected.reduce((a,x)=>a+x,0);if(sum!==b.roll)return toast(`Selected pegs must total ${b.roll}.`);b.open=b.open.filter(n=>!b.selected.includes(n));b.selected=[];b.roll=null;renderTiles();if(!b.open.length)endRun();else $('boxStatus').textContent=`${players[b.playerIndex]} closed the pegs. Roll again.`}
function endRun(){const b=state.box;if(!b.active)return;const name=players[b.playerIndex],score=b.open.reduce((a,x)=>a+x,0);b.scores[name]=score;if(b.playerIndex===0){b.playerIndex=1;b.open=[1,2,3,4,5,6,7,8,9];b.selected=[];b.roll=null;$('boxStatus').textContent=`Tammy scored ${score}. Aron begins — press Roll Dice.`;renderTiles()}else{b.active=false;const ts=b.scores.Tammy,as=b.scores.Aron;let msg;if(ts===as)msg=`Tie at ${ts}. No prize.`;else{const winner=ts<as?'Tammy':'Aron';changeMoney(winner,150000,'Shut the Box duel');msg=`${winner} wins $150,000. Scores: Tammy ${ts}, Aron ${as}.`}setPending(msg);$('boxStatus').textContent=msg}}
function renderTrivia(){const board=$('triviaBoard');if(!board)return;let html='';for(const [cat,qs] of trivia)html+=`<div class="cat">${cat}</div>`;for(let row=0;row<3;row++)for(let col=0;col<trivia.length;col++){const key=`${col}-${row}`,used=state.triviaUsed.has(key);html+=`<button class="clue" data-col="${col}" data-row="${row}" ${used?'disabled':''}>$${(row+1)*10000}</button>`}board.innerHTML=html;board.querySelectorAll('.clue').forEach(b=>b.onclick=()=>openClue(+b.dataset.col,+b.dataset.row))}
function openClue(col,row){if(!useMode('trivia'))return;const key=`${col}-${row}`,q=trivia[col][1][row],value=(row+1)*10000;state.pending=true;state.activeClue={key,q,value,correct:q[2]};$('triviaValue').textContent=trivia[col][0]+' — '+money(value);$('triviaClue').textContent=q[0];$('triviaChoices').innerHTML=q[1].map((x,i)=>`<button class="choice" data-i="${i}">${x}</button>`).join('');$('triviaChoices').querySelectorAll('button').forEach(b=>b.onclick=()=>answerClue(+b.dataset.i));$('triviaAnswer').classList.add('hidden');$('triviaFeedback').classList.add('hidden');$('continueClue').classList.add('hidden');$('revealClue').classList.remove('hidden');$('cancelClue').classList.remove('hidden');$('triviaModal').classList.remove('hidden');update()}
function answerClue(i){const a=state.activeClue;if(!a)return;state.triviaUsed.add(a.key);const good=i===a.correct,delta=good?a.value:-Math.floor(a.value/2);changeMoney(current(),delta,'Trivia');document.querySelectorAll('.choice').forEach((b,j)=>{b.disabled=true;b.classList.toggle('correct',j===a.correct);b.classList.toggle('wrong',j===i&&!good)});$('triviaFeedback').textContent=good?`Correct! ${current()} wins ${money(a.value)}.`:`Incorrect. ${current()} loses ${money(Math.abs(delta))}.`;$('triviaFeedback').classList.remove('hidden');$('continueClue').classList.remove('hidden');$('revealClue').classList.add('hidden');$('cancelClue').classList.add('hidden');setPending($('triviaFeedback').textContent);renderTrivia()}
function revealAnswer(){const a=state.activeClue;if(!a)return;state.triviaUsed.add(a.key);$('triviaAnswer').textContent='Correct answer: '+a.q[1][a.correct];$('triviaAnswer').classList.remove('hidden');$('continueClue').classList.remove('hidden');$('revealClue').classList.add('hidden');$('cancelClue').classList.add('hidden');setPending('Answer revealed. No money changed.');renderTrivia()}
function closeClue(){state.activeClue=null;$('triviaModal').classList.add('hidden')}
function cancelClue(){state.uses[current()].trivia=Math.max(0,state.uses[current()].trivia-1);state.pending=false;state.pendingMode=null;closeClue();update()}
function resetSecret(){state.secret=null;if($('secretResult'))$('secretResult').textContent='No secret round is active.'}
function secretMax(){return Math.max(0,Math.min(state.scores.Tammy,state.scores.Aron))}
function renderSecret(){if(!$('secretWager'))return;const active=!!state.secret?.active,max=secretMax();$('secretTammyBankroll').textContent=money(state.scores.Tammy);$('secretAronBankroll').textContent=money(state.scores.Aron);$('secretWagerHelp').textContent=max?`Maximum wager: ${money(max)}.`:'Use a $0 practice round until both players have money.';$('secretWager').disabled=active||state.pending&&!active;$('tammyGuess').disabled=!active;$('aronGuess').disabled=!active;$('revealSecret').disabled=!active;$('cancelSecret').disabled=!active;$('newSecret').disabled=state.pending||!state.started}
function secureNumber(){const a=new Uint32Array(1);crypto.getRandomValues(a);return 1+a[0]%100}
function lockSecret(){if(!useMode('secret'))return;let wager=Math.max(0,Math.floor((+$('secretWager').value||0)/5000)*5000);if(wager>secretMax()){state.uses[current()].secret--;state.pendingMode=null;return toast(`Maximum wager is ${money(secretMax())}.`)}state.secret={active:true,number:secureNumber(),wager};state.pending=true;$('secretLockStatus').textContent=`NUMBER LOCKED — ${money(wager)} wager. Enter both guesses.`;$('secretResult').textContent='The number is locked.';renderSecret();update()}
function revealSecret(){const s=state.secret;if(!s?.active)return;const t=+$('tammyGuess').value,a=+$('aronGuess').value;if(!Number.isInteger(t)||t<1||t>100||!Number.isInteger(a)||a<1||a>100)return toast('Enter both guesses from 1 to 100.');const td=Math.abs(t-s.number),ad=Math.abs(a-s.number);let msg;if(td===ad)msg='Tie. No money moves.';else{const w=td<ad?'Tammy':'Aron',l=other(w),before=state.scores[l];state.scores[l]=Math.max(0,state.scores[l]-s.wager);state.scores[w]+=s.wager;log(`${w} took ${money(s.wager)} from ${l}.`);handleBankruptcy(l,before,state.scores[l]);if(state.scores[w]>=state.target)finish(w);msg=`${w} was closer and takes ${money(s.wager)} from ${l}.`}s.active=false;$('secretLockStatus').textContent='Round settled.';$('secretResult').textContent=`Locked number: ${s.number}. Tammy guessed ${t}; Aron guessed ${a}. ${msg}`;setPending(msg);renderSecret()}
function cancelSecretRound(){if(!state.secret?.active)return;state.secret.active=false;$('secretLockStatus').textContent='Round cancelled.';setPending('Secret Number round cancelled.');renderSecret()}
function bind(){document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>openPane(b.dataset.pane)));$('startBtn').addEventListener('click',startGame);$('playAgainBtn').onclick=()=>{$('winner').classList.add('hidden');$('setup').classList.remove('hidden')};$('newGameBtn').onclick=()=>{if(confirm('Reset the entire game?'))$('setup').classList.remove('hidden')};$('completeBtn').onclick=completeTurn;$('skipBtn').onclick=skipTurn;$('undoBtn').onclick=undo;$('spinBtn').onclick=spinWheel;$('chipRack').onclick=e=>{const b=e.target.closest('[data-chip]');if(b)addChip(+b.dataset.chip)};$('undoChipBtn').onclick=undoChip;$('clearBetBtn').onclick=clearBet;$('dealBtn').onclick=dealBJ;$('hitBtn').onclick=hitBJ;$('standBtn').onclick=standBJ;$('shuffleShoeBtn').onclick=()=>{if(!state.bj.active){state.bj.deck=makeDeck();renderBJ();toast('Fresh deck shuffled.')}};$('rollBtn').onclick=rollDice;$('closeBtn').onclick=closeTiles;$('endRunBtn').onclick=endRun;$('tiles').onclick=e=>{const b=e.target.closest('.tile');if(b)toggleTile(+b.dataset.n)};$('revealClue').onclick=revealAnswer;$('cancelClue').onclick=cancelClue;$('continueClue').onclick=closeClue;$('newSecret').onclick=lockSecret;$('revealSecret').onclick=revealSecret;$('cancelSecret').onclick=cancelSecretRound;$('secretWagerChips').onclick=e=>{const b=e.target.closest('[data-secret-wager]');if(!b)return;$('secretWager').value=b.dataset.secretWager==='max'?secretMax():+b.dataset.secretWager};$('dismissInstall').onclick=$('hideInstall').onclick=()=>$('installCard').classList.remove('show');window.addEventListener('resize',drawWheel)}
function boot(){try{initUses();resetBJ();resetBox();resetSecret();renderTrivia();bind();update();drawWheel();document.documentElement.dataset.ready='true'}catch(err){console.error(err);$('startupError').textContent='Game startup error: '+err.message;$('startupError').classList.add('show')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();